# Generated by Django 3.2.25 on 2024-10-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.CharField(max_length=5000)),
                ('pasos', models.CharField(max_length=5000)),
                ('ingredientes', models.CharField(max_length=5000)),
                ('descripcion', models.CharField(max_length=5000)),
                ('imagen', models.ImageField(null=True, upload_to='recetas')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo.descripcion')),
            ],
        ),
    ]
