# Generated by Django 2.1.11 on 2019-10-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='recetas'),
        ),
    ]
