# Generated by Django 3.2.25 on 2024-10-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo.descripcion'),
        ),
    ]
