# Generated by Django 3.2.25 on 2024-10-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_auto_20241005_1606'),
        ('tipo', '0001_initial'),
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chefs.chef'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo.descripcion'),
        ),
    ]
