# Generated by Django 3.2.25 on 2024-10-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_auto_20241003_0330'),
        ('recetas', '0002_alter_recetas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chefs.chef'),
        ),
    ]
