# Generated by Django 3.2.25 on 2024-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='celular',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='chef',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
