# Generated by Django 3.2.25 on 2024-10-05 21:06

import apps.chefs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='celular',
            field=models.CharField(default=0, max_length=10, validators=[apps.chefs.models.validate_only_numbers]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chef',
            name='apellidos',
            field=models.CharField(max_length=70, validators=[apps.chefs.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='chef',
            name='nombres',
            field=models.CharField(max_length=70, validators=[apps.chefs.models.validate_only_letters]),
        ),
    ]
