# Generated by Django 3.2.25 on 2024-10-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_auto_20241005_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='chefs_fotos/'),
        ),
    ]
