# Generated by Django 3.2.25 on 2024-10-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_auto_20241005_2157'),
        ('chefs', '0002_auto_20241006_1332'),
    ]

    operations = [
    ]
