# Generated by Django 3.2.25 on 2024-10-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
